/**
 * Multi-provider catalog + channel playbooks for Autopilot AI pilots.
 * pricing: free | freemium | paid
 * availability: ready_free | needs_key
 */

export const CHANNELS = {
  whatsapp: {
    id: 'whatsapp',
    label: 'WhatsApp AI Pilot',
    short: 'WhatsApp',
    icon: '💬',
    description: 'Warm intros, slot offers, and follow-ups via WhatsApp Business APIs.',
    activityType: 'whatsapp',
    requires: 'phone',
    defaultDailyLimit: 80,
    defaultGoal: 'Book Practo demo / Prime intro',
    defaultSubject: '',
    defaultTemplate:
      'Hi {{name}}, this is Practo Enterprise. Clinics like {{company}} in your area are unlocking more patient bookings with Practo Reach & Prime. Can I share a 2-min overview today?',
    advanced: [
      'Template / HSM personalization with {{name}} {{company}}',
      'Phone-qualified audience only',
      'Daily send caps + dry-run mode',
      'Multi-provider: Meta Cloud, Gupshup, Exotel, MSG91, Twilio WhatsApp',
    ],
  },
  gmail: {
    id: 'gmail',
    label: 'Gmail AI Pilot',
    short: 'Gmail',
    icon: '📧',
    description: 'Multi-touch email nurture with subject lines and AI-ready copy.',
    activityType: 'email',
    requires: 'email',
    defaultDailyLimit: 60,
    defaultGoal: 'Nurture → proposal conversation',
    defaultSubject: '{{company}} × Practo — patient growth plan',
    defaultTemplate:
      'Dear {{name}},\n\nI noticed {{company}} and wanted to share how Practo Enterprise helps clinics grow discovery and bookings (Prime, Reach, Video).\n\nWould you be open to a short call this week?\n\nBest,\nPracto Enterprise',
    advanced: [
      'Subject + body templates',
      'Email-qualified audience only',
      'Providers: Gmail OAuth, SendGrid, Amazon SES, Resend, Mailgun',
      'Optional LLM rewrite when AI connector is enabled',
    ],
  },
  calls: {
    id: 'calls',
    label: 'Calls AI Pilot',
    short: 'Calls',
    icon: '📞',
    description: 'AI qualifier scripts and dial queues for high-intent clinic leads.',
    activityType: 'call',
    requires: 'phone',
    defaultDailyLimit: 40,
    defaultGoal: 'Qualify → book commercial walkthrough',
    defaultSubject: '',
    defaultTemplate:
      'Script: Confirm speaking with {{name}} at {{company}}. Pitch Practo Reach visibility + Prime appointments. Ask for decision-maker / marketing head. Book 15-min commercial suite review.',
    advanced: [
      'Call script playbook',
      'Phone-qualified dial list',
      'Providers: Twilio, Exotel, Knowlarity, Plivo, MyOperator',
      'Outcome logging into CRM activities',
    ],
  },
};

/** Multiple ready integration options per channel (+ shared AI / discovery) */
export const INTEGRATION_CATALOG = [
  // —— WhatsApp ——
  {
    provider: 'whatsapp_meta',
    label: 'WhatsApp Cloud API (Meta)',
    category: 'Messaging',
    channel: 'whatsapp',
    is_default: 1,
    pricing: 'paid',
    availability: 'needs_key',
    config: { phoneNumberId: '', wabaId: '', apiVersion: 'v19.0', templateNamespace: '', pricing: 'paid' },
    secrets: { accessToken: '' },
    notes: 'Official Meta Cloud API — production WhatsApp Business',
  },
  {
    provider: 'whatsapp_gupshup',
    label: 'Gupshup WhatsApp',
    category: 'Messaging',
    channel: 'whatsapp',
    is_default: 0,
    pricing: 'paid',
    availability: 'needs_key',
    config: { appName: '', sourceNumber: '', apiBase: 'https://api.gupshup.io', pricing: 'paid' },
    secrets: { apiKey: '' },
    notes: 'India-friendly WhatsApp BSP',
  },
  {
    provider: 'whatsapp_exotel',
    label: 'Exotel WhatsApp',
    category: 'Messaging',
    channel: 'whatsapp',
    is_default: 0,
    pricing: 'paid',
    availability: 'needs_key',
    config: { subdomain: '', from: '', pricing: 'paid' },
    secrets: { apiKey: '', apiToken: '' },
    notes: 'Exotel unified messaging for WhatsApp',
  },
  {
    provider: 'whatsapp_msg91',
    label: 'MSG91 WhatsApp',
    category: 'Messaging',
    channel: 'whatsapp',
    is_default: 0,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { integratedNumber: '', pricing: 'freemium' },
    secrets: { authKey: '' },
    notes: 'India BSP with free trial credits',
  },
  {
    provider: 'whatsapp_twilio',
    label: 'Twilio WhatsApp',
    category: 'Messaging',
    channel: 'whatsapp',
    is_default: 0,
    pricing: 'paid',
    availability: 'needs_key',
    config: { fromNumber: '', pricing: 'paid' },
    secrets: { accountSid: '', authToken: '' },
    notes: 'Twilio WhatsApp sender',
  },
  // —— Email ——
  {
    provider: 'gmail',
    label: 'Gmail / Google Workspace',
    category: 'Email',
    channel: 'gmail',
    is_default: 1,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { sender: '', scopes: 'gmail.send,gmail.readonly', pricing: 'freemium' },
    secrets: { oauthClientId: '', oauthClientSecret: '', refreshToken: '' },
    notes: 'OAuth for Gmail / Workspace send',
  },
  {
    provider: 'sendgrid_email',
    label: 'SendGrid Email',
    category: 'Email',
    channel: 'gmail',
    is_default: 0,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { fromEmail: '', fromName: 'Practo Enterprise', region: 'global', pricing: 'freemium' },
    secrets: { apiKey: '' },
    notes: 'Free tier available — transactional email',
  },
  {
    provider: 'amazon_ses',
    label: 'Amazon SES',
    category: 'Email',
    channel: 'gmail',
    is_default: 0,
    pricing: 'paid',
    availability: 'needs_key',
    config: { region: 'ap-south-1', fromEmail: '', pricing: 'paid' },
    secrets: { accessKeyId: '', secretAccessKey: '' },
    notes: 'AWS SES for high-volume outbound email',
  },
  {
    provider: 'resend_email',
    label: 'Resend Email',
    category: 'Email',
    channel: 'gmail',
    is_default: 0,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { fromEmail: '', pricing: 'freemium' },
    secrets: { apiKey: '' },
    notes: 'Modern email API with free daily quota',
  },
  {
    provider: 'mailgun_email',
    label: 'Mailgun Email',
    category: 'Email',
    channel: 'gmail',
    is_default: 0,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { domain: '', region: 'us', pricing: 'freemium' },
    secrets: { apiKey: '' },
    notes: 'Mailgun SMTP / API',
  },
  // —— Voice / Calls ——
  {
    provider: 'twilio_calls',
    label: 'Twilio Voice',
    category: 'Voice',
    channel: 'calls',
    is_default: 1,
    pricing: 'paid',
    availability: 'needs_key',
    config: { fromNumber: '', region: 'in1', pricing: 'paid' },
    secrets: { accountSid: '', authToken: '' },
    notes: 'Twilio programmable voice dialer',
  },
  {
    provider: 'exotel_calls',
    label: 'Exotel Voice',
    category: 'Voice',
    channel: 'calls',
    is_default: 0,
    pricing: 'paid',
    availability: 'needs_key',
    config: { subdomain: '', callerId: '', pricing: 'paid' },
    secrets: { apiKey: '', apiToken: '' },
    notes: 'India call center / click-to-call',
  },
  {
    provider: 'knowlarity_calls',
    label: 'Knowlarity Voice',
    category: 'Voice',
    channel: 'calls',
    is_default: 0,
    pricing: 'paid',
    availability: 'needs_key',
    config: { srNumber: '', channel: 'voice', pricing: 'paid' },
    secrets: { apiKey: '', authToken: '' },
    notes: 'Cloud telephony for sales dialers',
  },
  {
    provider: 'plivo_calls',
    label: 'Plivo Voice',
    category: 'Voice',
    channel: 'calls',
    is_default: 0,
    pricing: 'paid',
    availability: 'needs_key',
    config: { fromNumber: '', pricing: 'paid' },
    secrets: { authId: '', authToken: '' },
    notes: 'Plivo cloud calling',
  },
  {
    provider: 'myoperator_calls',
    label: 'MyOperator Voice',
    category: 'Voice',
    channel: 'calls',
    is_default: 0,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { companyId: '', pricing: 'freemium' },
    secrets: { apiKey: '' },
    notes: 'India IVR / click-to-call with trial',
  },
  // —— AI ——
  {
    provider: 'openai',
    label: 'OpenAI / LLM',
    category: 'AI',
    channel: 'ai',
    is_default: 1,
    pricing: 'paid',
    availability: 'needs_key',
    config: { model: 'gpt-4o-mini', temperature: 0.4, pricing: 'paid' },
    secrets: { apiKey: '' },
    notes: 'Personalize Autopilot copy when enabled',
  },
  {
    provider: 'google_gemini',
    label: 'Google Gemini',
    category: 'AI',
    channel: 'ai',
    is_default: 0,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { model: 'gemini-1.5-flash', pricing: 'freemium' },
    secrets: { apiKey: '' },
    notes: 'Free tier available for copy personalization',
  },
  {
    provider: 'anthropic_claude',
    label: 'Anthropic Claude',
    category: 'AI',
    channel: 'ai',
    is_default: 0,
    pricing: 'paid',
    availability: 'needs_key',
    config: { model: 'claude-3-5-haiku-latest', pricing: 'paid' },
    secrets: { apiKey: '' },
    notes: 'Claude for sales email / WhatsApp polish',
  },
  {
    provider: 'groq_llm',
    label: 'Groq (fast LLM)',
    category: 'AI',
    channel: 'ai',
    is_default: 0,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { model: 'llama-3.1-8b-instant', pricing: 'freemium' },
    secrets: { apiKey: '' },
    notes: 'Free-tier friendly fast inference',
  },
  // —— Discovery (free + paid) ——
  {
    provider: 'openstreetmap_nominatim',
    label: 'OpenStreetMap Nominatim (free)',
    category: 'Discovery',
    channel: 'discovery',
    is_default: 1,
    pricing: 'free',
    availability: 'ready_free',
    config: { countrycodes: 'in', rateLimitPerSec: 1, pricing: 'free' },
    secrets: {},
    notes: 'FREE — used automatically for locality clinic search (rate-limited)',
  },
  {
    provider: 'overpass_osm',
    label: 'OSM Overpass API (free)',
    category: 'Discovery',
    channel: 'discovery',
    is_default: 1,
    pricing: 'free',
    availability: 'ready_free',
    config: { endpoint: 'https://overpass-api.de/api/interpreter', pricing: 'free' },
    secrets: {},
    notes: 'FREE — pulls clinics/hospitals/dentists near zone localities',
  },
  {
    provider: 'google_maps',
    label: 'Google Maps Places API',
    category: 'Discovery',
    channel: 'discovery',
    is_default: 0,
    pricing: 'paid',
    availability: 'needs_key',
    config: { region: 'in', language: 'en', pricing: 'paid' },
    secrets: { apiKey: '' },
    notes: 'GMB / Places enrichment when key is set',
  },
  {
    provider: 'serpapi',
    label: 'SerpAPI (Google / Maps SERP)',
    category: 'Discovery',
    channel: 'discovery',
    is_default: 0,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { engine: 'google_maps', pricing: 'freemium' },
    secrets: { apiKey: '' },
    notes: 'Search-engine results + Maps pack (free trial)',
  },
  {
    provider: 'outscraper',
    label: 'Outscraper (GMB scrape)',
    category: 'Discovery',
    channel: 'discovery',
    is_default: 0,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { pricing: 'freemium' },
    secrets: { apiKey: '' },
    notes: 'Google My Business listings enrichment',
  },
  {
    provider: 'apify',
    label: 'Apify actors (web/GMB)',
    category: 'Discovery',
    channel: 'discovery',
    is_default: 0,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { actorId: '', pricing: 'freemium' },
    secrets: { token: '' },
    notes: 'Run scrapers for directories / websites',
  },
  {
    provider: 'practo',
    label: 'Practo API',
    category: 'Marketplace',
    channel: 'discovery',
    is_default: 1,
    pricing: 'paid',
    availability: 'needs_key',
    config: { baseUrl: 'https://api.practo.com', environment: 'sandbox', version: 'v1', pricing: 'paid' },
    secrets: { apiKey: '', clientId: '', clientSecret: '' },
    notes: 'Partner API for listing / product sync',
  },
  {
    provider: 'justdial',
    label: 'Justdial Partner API',
    category: 'Discovery',
    channel: 'discovery',
    is_default: 0,
    pricing: 'paid',
    availability: 'needs_key',
    config: { baseUrl: '', cityDefault: 'Bangalore', pricing: 'paid' },
    secrets: { apiKey: '' },
    notes: 'Optional listing enrichment',
  },
  {
    provider: 'hunter_email',
    label: 'Hunter.io Email Finder',
    category: 'Enrichment',
    channel: 'discovery',
    is_default: 0,
    pricing: 'freemium',
    availability: 'needs_key',
    config: { pricing: 'freemium' },
    secrets: { apiKey: '' },
    notes: 'Find clinic emails from domain (free monthly credits)',
  },
  {
    provider: 'webhook_outbound',
    label: 'Outbound Webhooks',
    category: 'Automation',
    channel: 'automation',
    is_default: 1,
    pricing: 'free',
    availability: 'ready_free',
    config: { leadCreatedUrl: '', stageChangedUrl: '', campaignRunUrl: '', pricing: 'free' },
    secrets: { signingSecret: '' },
    notes: 'FREE to configure — push CRM / Autopilot events to your stack',
  },
];

export function personalizeTemplate(template, lead, extras = {}) {
  const first = (lead.name || 'Doctor').split(' ')[0];
  return String(template || '')
    .replaceAll('{{name}}', first)
    .replaceAll('{{full_name}}', lead.name || first)
    .replaceAll('{{company}}', lead.company || 'your clinic')
    .replaceAll('{{phone}}', lead.phone || '')
    .replaceAll('{{email}}', lead.email || '')
    .replaceAll('{{title}}', lead.title || '')
    .replaceAll('{{subject}}', extras.subject || '');
}

export function channelMeta(channel) {
  return CHANNELS[channel] || CHANNELS.whatsapp;
}

export function catalogByProvider(provider) {
  return INTEGRATION_CATALOG.find((p) => p.provider === provider) || null;
}
